# Generated by Django 3.2.4 on 2023-02-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('q', 'q'), ('l', 'l'), ('ml', 'ml'), ('mm', 'mm'), ('cm', 'cm'), ('inch', 'inch'), ('m', 'm'), ('count', 'count')], max_length=5),
        ),
    ]
