# Generated by Django 3.2.4 on 2023-03-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='image1',
            field=models.FileField(default='', max_length=300, upload_to='Animals', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='animals',
            name='image2',
            field=models.FileField(max_length=300, null=True, upload_to='Animals', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='animals',
            name='image3',
            field=models.FileField(max_length=300, null=True, upload_to='Animals', verbose_name='Image 3'),
        ),
    ]
