# Generated by Django 3.2.4 on 2023-03-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='qualification',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
