# Generated by Django 3.2.4 on 2023-03-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230314_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_of_the_week',
            name='an_week_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='image2',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='Animals', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='image3',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='Animals', verbose_name='Image 3'),
        ),
    ]
