# Generated by Django 3.2.4 on 2023-03-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applications_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='reason',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='applications',
            name='qualification',
            field=models.CharField(max_length=20),
        ),
    ]
