# Generated by Django 3.2.4 on 2023-03-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230326_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdetails',
            name='expense',
            field=models.BigIntegerField(default=0),
        ),
    ]
