# Generated by Django 3.2.4 on 2023-03-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transferdetails_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponserdetails',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sponserdetails',
            name='edate',
        ),
        migrations.RemoveField(
            model_name='sponserdetails',
            name='sdate',
        ),
        migrations.AddField(
            model_name='sponseredanimals',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sponseredanimals',
            name='edate',
            field=models.DateField(null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='sponseredanimals',
            name='sdate',
            field=models.DateField(null=True, verbose_name='Start date'),
        ),
    ]
