# Generated by Django 3.2.4 on 2023-03-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_animals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
