# Generated by Django 3.2.4 on 2023-03-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_animals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sickness_details',
            name='sdate',
            field=models.DateField(verbose_name='Reported date'),
        ),
    ]
