# Generated by Django 3.2.4 on 2023-04-02 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230330_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponseredanimals',
            name='edate',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='sponseredanimals',
            name='sdate',
            field=models.DateField(default=datetime.datetime(2023, 4, 2, 15, 1, 54, 99039, tzinfo=utc), verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(max_length=32),
        ),
    ]
