# Generated by Django 3.2.4 on 2023-03-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_sickness_details_sdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Fadult',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Fchild',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Iadult',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Ichild',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='students',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reporting_date',
            field=models.DateField(verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reporting_time',
            field=models.CharField(choices=[('morning', 'morning'), ('noon', 'noon')], default='morning', max_length=10, verbose_name='Booking Slot'),
        ),
        migrations.CreateModel(
            name='BookedCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ticketrate')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ticket')),
            ],
        ),
    ]
