# Generated by Django 3.2.4 on 2023-03-19 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230319_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Guide',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.staffs'),
        ),
    ]
