# Generated by Django 3.2.4 on 2023-03-19 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_ticket_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staffs'),
        ),
    ]
