# Generated by Django 3.2.4 on 2023-03-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_ticket_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcatagory',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookedcatagory',
            name='catagory',
            field=models.CharField(max_length=20),
        ),
    ]
