# Generated by Django 3.2.4 on 2023-04-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_users_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
