# Generated by Django 3.2.4 on 2023-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_users_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
    ]
