# Generated by Django 3.2.4 on 2023-04-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_staffs_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponserdetails',
            name='notes',
            field=models.CharField(max_length=100, null=True, verbose_name='Notes'),
        ),
    ]
