# Generated by Django 3.2.4 on 2023-04-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_sponserdetails_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponserdetails',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notes'),
        ),
    ]
