# Generated by Django 3.2.4 on 2023-04-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_sponserdetails_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoodetails',
            name='total_animal_capacity',
            field=models.IntegerField(default=0, verbose_name='Maximum animal capacity'),
        ),
    ]
