# Generated by Django 3.2.4 on 2023-04-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_zoodetails_total_animal_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdetails',
            name='transfer_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='transferdetails',
            name='transport_type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
