# Generated by Django 3.2.4 on 2023-04-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230409_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdetails',
            name='transport_company',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='transferdetails',
            name='transporter_contact',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transferdetails',
            name='transporter_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
