# Generated by Django 3.2.4 on 2023-04-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20230409_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdetails',
            name='transporter_contact',
            field=models.BigIntegerField(default=None),
        ),
    ]
