# Generated by Django 3.2.4 on 2023-04-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_transferdetails_transporter_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zootimings',
            name='close_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='zootimings',
            name='open_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
