# Generated by Django 3.2.4 on 2023-04-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_zootimings_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='sickness_details',
            name='consumption',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
