# Generated by Django 3.2.4 on 2023-04-19 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20230419_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdetails',
            name='order',
            field=models.CharField(max_length=30, verbose_name='Order No.'),
        ),
        migrations.CreateModel(
            name='ConsumptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('dose', models.IntegerField()),
                ('sick_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sickness_details')),
            ],
        ),
    ]
