# Generated by Django 3.2.4 on 2023-04-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20230419_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptiondetails',
            name='date',
            field=models.DateField(),
        ),
    ]
