# Generated by Django 3.2.4 on 2023-04-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_ticketratehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalTicketCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateField(auto_now_add=True)),
                ('catagory', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ticketrate',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Catagory'),
        ),
    ]
