# Generated by Django 3.2.4 on 2023-04-27 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20230426_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalTicketCount',
        ),
    ]
