# Generated by Django 3.2.4 on 2023-05-04 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_delete_totalticketcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_of_the_week',
            name='performance',
            field=models.FileField(max_length=300, upload_to='performances', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'mp4', 'png'])]),
        ),
        migrations.AlterField(
            model_name='animals',
            name='image1',
            field=models.ImageField(max_length=300, upload_to='Animals', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='image2',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='Animals', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='image3',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='Animals', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eimage',
            field=models.FileField(max_length=300, upload_to='events', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id_card',
            field=models.FileField(max_length=300, upload_to='id', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
