# Generated by Django 3.2.4 on 2023-05-04 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20230504_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='image1',
            field=models.ImageField(max_length=300, upload_to='Animals', validators=[django.core.validators.validate_image_file_extension], verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='image2',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='Animals', validators=[django.core.validators.validate_image_file_extension], verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='image3',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='Animals', validators=[django.core.validators.validate_image_file_extension], verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(default='null', max_length=300, upload_to='DP', validators=[django.core.validators.validate_image_file_extension], verbose_name='profile photo'),
        ),
    ]
