# Generated by Django 3.2.4 on 2023-05-05 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20230504_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
