# Generated by Django 3.2.4 on 2023-05-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_staffs_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismantledEnclosures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enclosure', models.CharField(max_length=20, verbose_name='Enclosure name')),
                ('order', models.CharField(max_length=20, verbose_name='Order ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(max_length=100, verbose_name='Dismantle reason')),
            ],
        ),
    ]
