# Generated by Django 3.2.4 on 2023-05-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_dismantledenclosures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dismantledenclosures',
            name='date',
            field=models.DateField(),
        ),
    ]
