# Generated by Django 3.2.4 on 2023-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20230519_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='expire',
            field=models.DateField(default=None, null=True, verbose_name='Expired date'),
        ),
    ]
