# Generated by Django 3.2.4 on 2023-05-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_medicines_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='order',
            field=models.CharField(default=None, max_length=20, verbose_name='Order ID'),
        ),
    ]
