# Generated by Django 3.2.4 on 2023-05-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_jobvacancy_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='vend_time',
            field=models.TimeField(default=None, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='vstart_time',
            field=models.TimeField(default=None, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='vend',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='vposition',
            field=models.CharField(max_length=25, verbose_name='Vacancy Position'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='vstart',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='vstatus',
            field=models.CharField(default='available', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='vtype',
            field=models.CharField(choices=[('temporary', 'temporary'), ('permenant', 'permenant')], max_length=10, verbose_name='Vacancy Type'),
        ),
    ]
