# Generated by Django 3.2.4 on 2023-05-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20230521_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
    ]
