# Generated by Django 3.2.4 on 2023-05-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_jobvacancy_vtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferdetails',
            name='transfer_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transferdetails',
            name='transfer_to',
            field=models.CharField(max_length=50),
        ),
    ]
